-- MySQL Script generated by MySQL Workbench 
-- Tue Jun 19 00:45:49 2018 
-- Model: New Model    Version: 1.0 
-- MySQL Workbench Forward Engineering 
 
 
 
-- ----------------------------------------------------- 
-- Schema appers 
-- ----------------------------------------------------- 
CREATE DATABASE IF NOT EXISTS `appers`; 
USE `appers`; 
 
/*
MySQL Backup
Source Server Version: 5.5.5
Source Database: appers
Date: 7/2/2018 16:18:04
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
--  Table structure for `actor`
-- ----------------------------
DROP TABLE IF EXISTS `actor`;
CREATE TABLE `actor` (
  `id_actor` int(11) NOT NULL,
  `nombre` varchar(32) NOT NULL,
  `descripcion` text,
  `num_actual` int(11) DEFAULT NULL,
  `num_futuro` int(11) DEFAULT NULL,
  `num_de_contactables` int(11) DEFAULT NULL,
  `ref_proyecto` int(11) NOT NULL,
  PRIMARY KEY (`id_actor`),
  KEY `ref_proyecto` (`ref_proyecto`),
  CONSTRAINT `actor_ibfk_1` FOREIGN KEY (`ref_proyecto`) REFERENCES `proyecto` (`id_proyecto`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `asociacion`
-- ----------------------------
DROP TABLE IF EXISTS `asociacion`;
CREATE TABLE `asociacion` (
  `req_usuario` int(11) NOT NULL,
  `req_software` int(11) NOT NULL,
  KEY `req_usuario` (`req_usuario`),
  KEY `req_software` (`req_software`),
  CONSTRAINT `asociacion_ibfk_1` FOREIGN KEY (`req_usuario`) REFERENCES `requisito` (`id_requisito`),
  CONSTRAINT `asociacion_ibfk_2` FOREIGN KEY (`req_software`) REFERENCES `requisito` (`id_requisito`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `caso_de_uso`
-- ----------------------------
DROP TABLE IF EXISTS `caso_de_uso`;
CREATE TABLE `caso_de_uso` (
  `id_caso_de_uso` int(11) NOT NULL,
  `ref_proyecto` int(11) NOT NULL,
  `ruta_imagen` text,
  PRIMARY KEY (`id_caso_de_uso`),
  KEY `ref_proyecto` (`ref_proyecto`),
  CONSTRAINT `caso_de_uso_ibfk_1` FOREIGN KEY (`ref_proyecto`) REFERENCES `proyecto` (`id_proyecto`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `modificacion_ders`
-- ----------------------------
DROP TABLE IF EXISTS `modificacion_ders`;
CREATE TABLE `modificacion_ders` (
  `id_modificacion` int(11) NOT NULL,
  `version` float NOT NULL,
  `ref_proyecto` int(11) NOT NULL,
  `fecha` date DEFAULT NULL,
  `ref_autor_modificacion` varchar(12) NOT NULL,
  PRIMARY KEY (`id_modificacion`),
  KEY `ref_proyecto` (`ref_proyecto`),
  KEY `ref_autor_modificacion` (`ref_autor_modificacion`),
  CONSTRAINT `modificacion_ders_ibfk_1` FOREIGN KEY (`ref_proyecto`) REFERENCES `proyecto` (`id_proyecto`),
  CONSTRAINT `modificacion_ders_ibfk_2` FOREIGN KEY (`ref_autor_modificacion`) REFERENCES `usuario` (`rut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `proyecto`
-- ----------------------------
DROP TABLE IF EXISTS `proyecto`;
CREATE TABLE `proyecto` (
  `id_proyecto` int(11) NOT NULL,
  `nombre` varchar(128) DEFAULT NULL,
  `proposito` text,
  `alcance` text,
  `contexto` text,
  `definiciones` text,
  `acronimos` text,
  `abreviaturas` text,
  `referencias` text,
  `ambiente_operacional` text,
  `relacion_con_otros_proyectos` text,
  PRIMARY KEY (`id_proyecto`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `requisito`
-- ----------------------------
DROP TABLE IF EXISTS `requisito`;
CREATE TABLE `requisito` (
  `id_requisito` int(11) NOT NULL,
  `nombre` text,
  `descripcion` text,
  `prioridad` varchar(8) DEFAULT NULL,
  `categoria` varchar(12) DEFAULT NULL,
  `fuente` varchar(20) DEFAULT NULL,
  `estabilidad` varchar(11) DEFAULT NULL,
  `estado` varchar(13) DEFAULT NULL,
  `ref_proyecto` int(11) DEFAULT NULL,
  `tipo` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`id_requisito`),
  KEY `ref_proyecto` (`ref_proyecto`),
  CONSTRAINT `requisito_ibfk_1` FOREIGN KEY (`ref_proyecto`) REFERENCES `proyecto` (`id_proyecto`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `roles`
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `Id` varchar(128) NOT NULL,
  `Name` varchar(256) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `userclaims`
-- ----------------------------
DROP TABLE IF EXISTS `userclaims`;
CREATE TABLE `userclaims` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `UserId` varchar(128) NOT NULL,
  `ClaimType` longtext,
  `ClaimValue` longtext,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Id` (`Id`),
  KEY `UserId` (`UserId`),
  CONSTRAINT `ApplicationUser_Claims` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `userlogins`
-- ----------------------------
DROP TABLE IF EXISTS `userlogins`;
CREATE TABLE `userlogins` (
  `LoginProvider` varchar(128) NOT NULL,
  `ProviderKey` varchar(128) NOT NULL,
  `UserId` varchar(128) NOT NULL,
  PRIMARY KEY (`LoginProvider`,`ProviderKey`,`UserId`),
  KEY `ApplicationUser_Logins` (`UserId`),
  CONSTRAINT `ApplicationUser_Logins` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `userroles`
-- ----------------------------
DROP TABLE IF EXISTS `userroles`;
CREATE TABLE `userroles` (
  `UserId` varchar(128) NOT NULL,
  `RoleId` varchar(128) NOT NULL,
  PRIMARY KEY (`UserId`,`RoleId`),
  KEY `IdentityRole_Users` (`RoleId`),
  CONSTRAINT `ApplicationUser_Roles` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `IdentityRole_Users` FOREIGN KEY (`RoleId`) REFERENCES `roles` (`Id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `users`
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `Id` varchar(128) NOT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `EmailConfirmed` tinyint(1) NOT NULL,
  `PasswordHash` longtext,
  `SecurityStamp` longtext,
  `PhoneNumber` longtext,
  `PhoneNumberConfirmed` tinyint(1) NOT NULL,
  `TwoFactorEnabled` tinyint(1) NOT NULL,
  `LockoutEndDateUtc` datetime DEFAULT NULL,
  `LockoutEnabled` tinyint(1) NOT NULL,
  `AccessFailedCount` int(11) NOT NULL,
  `UserName` varchar(256) NOT NULL,
  `Rut` varchar(12) NOT NULL UNIQUE,
  `Tipo` varchar(20) NOT NULL,
  `Estado` bit(1) NOT NULL,
  `Nombre` varchar(256) NOT NULL,
  `Apellido` varchar(256) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `usuario`
-- ----------------------------
DROP TABLE IF EXISTS `usuario`;
CREATE TABLE `usuario` (
  `rut` varchar(12) NOT NULL,
  `nombre` varchar(50) NOT NULL,
  `correo_electronico` varchar(35) NOT NULL,
  `contrasenia` varchar(16) NOT NULL,
  `tipo` varchar(20) NOT NULL,
  `estado` bit(1) NOT NULL,
  PRIMARY KEY (`rut`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `vinculo_actor_requisito`
-- ----------------------------
DROP TABLE IF EXISTS `vinculo_actor_requisito`;
CREATE TABLE `vinculo_actor_requisito` (
  `ref_actor` int(11) NOT NULL,
  `ref_req` int(11) NOT NULL,
  KEY `ref_actor` (`ref_actor`),
  KEY `ref_req` (`ref_req`),
  CONSTRAINT `vinculo_actor_requisito_ibfk_1` FOREIGN KEY (`ref_actor`) REFERENCES `actor` (`id_actor`),
  CONSTRAINT `vinculo_actor_requisito_ibfk_2` FOREIGN KEY (`ref_req`) REFERENCES `requisito` (`id_requisito`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `vinculo_usuario_proyecto`
-- ----------------------------
DROP TABLE IF EXISTS `vinculo_usuario_proyecto`;
CREATE TABLE `vinculo_usuario_proyecto` (
  `ref_usuario` varchar(12) NOT NULL,
  `ref_proyecto` int(11) NOT NULL,
  `rol` varchar(30) NOT NULL,
  KEY `ref_usuario` (`ref_usuario`),
  KEY `ref_proyecto` (`ref_proyecto`),
  CONSTRAINT `vinculo_usuario_proyecto_ibfk_1` FOREIGN KEY (`ref_usuario`) REFERENCES `usuario` (`rut`),
  CONSTRAINT `vinculo_usuario_proyecto_ibfk_2` FOREIGN KEY (`ref_proyecto`) REFERENCES `proyecto` (`id_proyecto`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
--  Records 
-- ----------------------------
INSERT INTO `users` VALUES ('507dab6a-7cb5-423e-98b1-e72c82c33b46','gabriel_sanhueza100@hotmail.com','0','AK26189T50eAfw8PSQ6QbArEG8xf2Z3NeXo9hCCSVDeaI8t1rSwGdq3RsCYl66Vhyw==','cff85bb9-7bdc-48e3-8068-abf927244c4f',NULL,'0','0',NULL,'1','0','Gabriel Sanhuza','19084004','SYSADMIN','', 'Gabriel', 'Sanhueza');
INSERT INTO `usuario` VALUES ('19084004-2','Gabriel','hola@hotmail.com','hola','user',''), ('19084004-3','Diego','holoholo@hotmail.com','chao','user','');
