-- MySQL Script generated by MySQL Workbench
-- Tue Jul 10 14:56:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE DATABASE `appers` DEFAULT CHARACTER SET utf8;
USE `appers`;

-- -----------------------------------------------------
-- Table `appers`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Proyecto` (
  `id_proyecto` INT NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `proposito` TEXT NULL,
  `alcance` TEXT NULL,
  `contexto` TEXT NULL,
  `definiciones` TEXT NULL,
  `acronimos` TEXT NULL,
  `abreviaturas` TEXT NULL,
  `referencias` TEXT NULL,
  `ambiente_operacional` TEXT NULL,
  `relacion_con_otros_proyectos` TEXT NULL,
  `estado` TEXT NULL,
  PRIMARY KEY (`id_proyecto`)
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `Id` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(256) DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT NULL,
  `SecurityStamp` LONGTEXT NULL,
  `PhoneNumber` LONGTEXT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEndDateUtc` DATETIME DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT(11) NOT NULL,
  `UserName` VARCHAR(256) NOT NULL,
  `Rut` VARCHAR(12) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Estado` BIT(1) NOT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Modificacion_DERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Modificacion_DERS` (
  `id_modificacion` INT NOT NULL,
  `version` FLOAT NULL,
  `ref_proyecto` INT NULL,
  `fecha` DATE NULL,
  `ref_autor_modificacion` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_modificacion`),
  CONSTRAINT `ref_proyecto6`
    FOREIGN KEY (`ref_proyecto`)
    REFERENCES `appers`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `referencia_autor`
    FOREIGN KEY (`ref_autor_modificacion`)
    REFERENCES `appers`.`users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Vinculo_usuario_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Vinculo_usuario_proyecto` (
  `ref_usuario` VARCHAR(128) NOT NULL,
  `ref_proyecto` INT NOT NULL,
  `rol` VARCHAR(30) NOT NULL,
  CONSTRAINT `referencia_usuario`
    FOREIGN KEY (`ref_usuario`)
    REFERENCES `appers`.`users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ref_proyecto1`
    FOREIGN KEY (`ref_proyecto`)
    REFERENCES `appers`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Caso_de_uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Caso_de_uso` (
  `id_caso_de_uso` INT NOT NULL,
  `ref_proyecto` INT NOT NULL,
  `ruta_imagen` TEXT NULL,
  PRIMARY KEY (`id_caso_de_uso`),
  CONSTRAINT `ref_proyecto4`
    FOREIGN KEY (`ref_proyecto`)
    REFERENCES `appers`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Actor` (
  `id_actor` INT NOT NULL,
  `nombre` VARCHAR(32) NULL,
  `descripcion` TEXT NULL,
  `num_actual` INT NULL,
  `num_futuro` INT NULL,
  `num_de_contactables` INT NULL,
  `ref_proyecto` INT NULL,
  PRIMARY KEY (`id_actor`),
  CONSTRAINT `ref_proyecto5`
    FOREIGN KEY (`ref_proyecto`)
    REFERENCES `appers`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Requisito` (
  `id_requisito` INT NOT NULL,
  `nombre` TEXT NOT NULL,
  `descripcion` TEXT NULL,
  `prioridad` VARCHAR(8) NULL,
  `categoria` VARCHAR(12) NULL,
  `fuente` VARCHAR(20) NULL,
  `estabilidad` VARCHAR(11) NULL,
  `estado` VARCHAR(13) NULL,
  `ref_proyecto` INT NULL,
  `tipo` VARCHAR(8) NULL,
  PRIMARY KEY (`id_requisito`),
  CONSTRAINT `ref_proyecto3`
    FOREIGN KEY (`ref_proyecto`)
    REFERENCES `appers`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Asociacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Asociacion` (
  `req_usuario` INT NOT NULL,
  `req_software` INT NOT NULL,
  CONSTRAINT `asociacion_1`
    FOREIGN KEY (`req_usuario`)
    REFERENCES `appers`.`Requisito` (`id_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asociacion_2`
    FOREIGN KEY (`req_software`)
    REFERENCES `appers`.`Requisito` (`id_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Vinculo_actor_requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Vinculo_actor_requisito` (
  `ref_actor` INT NOT NULL,
  `ref_req` INT NOT NULL,
  INDEX `referencia_req_usuario_idx` (`ref_req` ASC),
  CONSTRAINT `referencia_actor`
    FOREIGN KEY (`ref_actor`)
    REFERENCES `appers`.`Actor` (`id_actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `referencia_req`
    FOREIGN KEY (`ref_req`)
    REFERENCES `appers`.`Requisito` (`id_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`Solicitud_vinculacion_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Solicitud_vinculacion_proyecto` (
  `ref_proyecto` INT NOT NULL,
  `ref_solicitante` VARCHAR(128) NOT NULL,
  CONSTRAINT `referencia_solicitante`
    FOREIGN KEY (`ref_solicitante`)
    REFERENCES `appers`.`users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ref_proyecto2`
    FOREIGN KEY (`ref_proyecto`)
    REFERENCES `appers`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `appers`.`Solicitud_jefeproyecto_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appers`.`Solicitud_jefeproyecto_usuario`(
	`ref_proyecto` INT NOT NULL,
	`ref_destinario` VARCHAR(128) NOT NULL,
	`estado` INT (1) NOT NULL,-- 0 = pendiente, 1= aceptada,2 = rechazada
	CONSTRAINT `referencia_proyecto`
	  FOREIGN KEY(`ref_proyecto`)
	  REFERENCES `appers`.`Proyecto`(`id_proyecto`)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION,
	CONSTRAINT `referencia_destinario`
	  FOREIGN KEY (`ref_destinario`)
	  REFERENCES `appers`.`users` (`Id`)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `appers`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `Id` VARCHAR(128) NOT NULL,
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`userclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userclaims` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserId` VARCHAR(128) NOT NULL,
  `ClaimType` LONGTEXT NULL,
  `ClaimValue` LONGTEXT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Id` (`Id`),
  KEY `UserId` (`UserId`),
  CONSTRAINT `ApplicationUser_Claims`
    FOREIGN KEY (`UserId`)
    REFERENCES `users` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`userlogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userlogins` (
  `LoginProvider` VARCHAR(128) NOT NULL,
  `ProviderKey` VARCHAR(128) NOT NULL,
  `UserId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`, `UserId`),
  KEY `ApplicationUser_Logins` (`UserId`),
  CONSTRAINT `ApplicationUser_Logins`
    FOREIGN KEY (`UserId`)
    REFERENCES `users` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appers`.`userroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userroles` (
  `UserId` VARCHAR(128) NOT NULL,
  `RoleId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  KEY `IdentityRole_Users` (`RoleId`),
  CONSTRAINT `ApplicationUser_Roles`
    FOREIGN KEY (`UserId`)
    REFERENCES `users` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `IdentityRole_Users`
    FOREIGN KEY (`RoleId`)
    REFERENCES `roles` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
